@baseUrl = http://localhost:3000
@json = application/json

### Get Posts
GET {{baseUrl}}/posts

### Listar alunos
GET {{baseUrl}}/alunos

### Criar aluno (usa timestamp p/ evitar e-mail duplicado)
POST {{baseUrl}}/posts
Content-Type: {{json}}

{
    "autor_id": 2,
    "titulo": "Rodolfo {{$timestamp}}",
    "conteudo": "rodolfo{{$timestamp}}@example.com"
}
