name: CI/CD com Testes e Banco de Dados

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    env:
      APP_PORT: 3000
      PORT: 3000
      NODE_ENV: test
      JWT_SECRET: ci_cd_secret



      ENVIRONMENT: test
      POSTGRES_HOST: postgresdb
      POSTGRES_DB: educablog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Secure_Password_For_CI_123!
      POSTGRES_PORT: 5432

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Aguardando 10s para o Postgres iniciar..."
          sleep 10

      - name: Run Integration Tests (Vitest)
        run: npm prod
